<?=$this->fetch('_head.phtml')?>
<?php
if (isset($info)){
    ?>
    <div class="col-sm-8">

    </div>
    <div class="col-sm-4">
        <div class="alert alert-danger" role="alert">
            <?=$info?>
        </div>
    </div>

<?php
}
?>
    <form method="post" class="form-signin" style="max-width: 330px; margin: 0 auto;">
        <h2 class="form-signin-heading">Вход</h2>
        <label for="inputUsername" class="sr-only">Username</label>
        <input type="text" name="username" id="inputUsername" placeholder="username" class="form-control"  required="true" autofocus="">
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required="">
        <br/>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>

<?=$this->fetch('_bottom.phtml')?>