<?=$this->fetch('_head.phtml')?>
<?=$this->fetch('_menu.phtml');?>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Проблема</th>
            <th>Решение</th>
            <th>Оценка</th>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach ($tasks as $task){
        ?>
        <tr>
            <td><?=htmlspecialchars($task->issue)?></td>
            <td><?=htmlspecialchars($task->solution)?></td>
            <td><?=htmlspecialchars($task->rate)?></td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>

<?=$this->fetch('_bottom.phtml')?>