<?=$this->fetch('_head.phtml')?>
<?=$this->fetch('_menu.phtml');?>
<table class="table table-hover tasks-list">
    <thead>
        <tr>
            <th>Проблема</th>
            <th>Решение</th>
            <th>Оценка</th>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach ($tasks as $task){
        ?>
        <tr>
            <td><?=htmlspecialchars($task->issue)?></td>
            <td><?=htmlspecialchars($task->solution)?></td>
            <td>
                <input type="number" name="rate" data-max="5" data-min="1" value="<?=$task->rate?>" task-id="<?=$task->id?>" class="rating" />
            </td>
        </tr>
    <?php
    }
    ?>

    </tbody>
</table>



<?=$this->fetch('_bottom.phtml')?>